spring:
  application:
    name: introme
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # database 연동
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/introme_dev?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    username: inlee
    password: 2580

  #spring data jpa 설정
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect